"""add flag and propensity

Revision ID: 16e91fe8571a
Revises: 99d8061c6ba8
Create Date: 2026-03-27 15:37:54.148146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e91fe8571a'
down_revision: Union[str, Sequence[str], None] = '99d8061c6ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_records', sa.Column('flag1', sa.String(length=50), nullable=True))
    op.add_column('collection_records', sa.Column('propensity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_records', 'propensity')
    op.drop_column('collection_records', 'flag1')
    # ### end Alembic commands ###
