"""Add Life and Health insurance tables

Revision ID: 1a3b7d21c51d
Revises: e8de06ee12e3
Create Date: 2026-03-26 12:15:12.536439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3b7d21c51d'
down_revision: Union[str, Sequence[str], None] = 'e8de06ee12e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_retention_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('policy_no', sa.String(length=20), nullable=False),
    sa.Column('cust_id', sa.String(length=15), nullable=True),
    sa.Column('agent_code', sa.String(length=15), nullable=True),
    sa.Column('policy_status', sa.String(length=20), nullable=True),
    sa.Column('policy_issue_date', sa.Date(), nullable=True),
    sa.Column('paid_to_date', sa.Date(), nullable=True),
    sa.Column('policy_lapse_date', sa.Date(), nullable=True),
    sa.Column('max_ri_date', sa.Date(), nullable=True),
    sa.Column('quotation_valid_upto_date', sa.Date(), nullable=True),
    sa.Column('policy_paying_frequency', sa.SmallInteger(), nullable=True),
    sa.Column('policy_paying_term', sa.SmallInteger(), nullable=True),
    sa.Column('policy_year', sa.String(length=30), nullable=True),
    sa.Column('policy_source_code', sa.String(length=20), nullable=True),
    sa.Column('product_type', sa.String(length=30), nullable=True),
    sa.Column('product_name_raw', sa.String(length=200), nullable=True),
    sa.Column('product_code', sa.String(length=10), nullable=True),
    sa.Column('product_category_raw', sa.String(length=100), nullable=True),
    sa.Column('productgroup', sa.String(length=5), nullable=True),
    sa.Column('outstanding_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('modal_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('act_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_in_suspence', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_charged', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('policy_ageing', sa.Integer(), nullable=True),
    sa.Column('lapse_ageing', sa.Integer(), nullable=True),
    sa.Column('policy_ageing_band', sa.String(length=10), nullable=True),
    sa.Column('propensity_band', sa.String(length=20), nullable=True),
    sa.Column('ptd_slab', sa.String(length=15), nullable=True),
    sa.Column('client_bucket', sa.String(length=20), nullable=True),
    sa.Column('priority_bucket', sa.String(length=50), nullable=True),
    sa.Column('sub_campaign_name', sa.String(length=30), nullable=True),
    sa.Column('campaign_type_code', sa.String(length=20), nullable=True),
    sa.Column('agent_status', sa.String(length=15), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('source_agency_name', sa.String(length=30), nullable=True),
    sa.Column('payment_mode', sa.String(length=5), nullable=True),
    sa.Column('branch_code', sa.String(length=15), nullable=True),
    sa.Column('branch_name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('zone', sa.String(length=30), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('pmt_flag', sa.Boolean(), nullable=False),
    sa.Column('lot_date', sa.Date(), nullable=False),
    sa.Column('dataset_month', sa.Date(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('months_in_campaign', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'lot_date')
    )
    op.create_table('life_campaign_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('policy_no', sa.String(length=20), nullable=False),
    sa.Column('cust_id', sa.String(length=15), nullable=True),
    sa.Column('agent_code', sa.String(length=15), nullable=True),
    sa.Column('policy_status', sa.String(length=20), nullable=True),
    sa.Column('policy_issue_date', sa.Date(), nullable=True),
    sa.Column('paid_to_date', sa.Date(), nullable=True),
    sa.Column('policy_lapse_date', sa.Date(), nullable=True),
    sa.Column('max_ri_date', sa.Date(), nullable=True),
    sa.Column('quotation_valid_upto_date', sa.Date(), nullable=True),
    sa.Column('policy_paying_frequency', sa.SmallInteger(), nullable=True),
    sa.Column('policy_paying_term', sa.SmallInteger(), nullable=True),
    sa.Column('policy_year', sa.String(length=30), nullable=True),
    sa.Column('policy_source_code', sa.String(length=20), nullable=True),
    sa.Column('product_type', sa.String(length=30), nullable=True),
    sa.Column('product_name_raw', sa.String(length=200), nullable=True),
    sa.Column('product_code', sa.String(length=10), nullable=True),
    sa.Column('product_category_raw', sa.String(length=100), nullable=True),
    sa.Column('productgroup', sa.String(length=5), nullable=True),
    sa.Column('outstanding_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('modal_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('act_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_in_suspence', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_charged', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('policy_ageing', sa.Integer(), nullable=True),
    sa.Column('lapse_ageing', sa.Integer(), nullable=True),
    sa.Column('policy_ageing_band', sa.String(length=10), nullable=True),
    sa.Column('propensity_band', sa.String(length=20), nullable=True),
    sa.Column('ptd_slab', sa.String(length=15), nullable=True),
    sa.Column('client_bucket', sa.String(length=20), nullable=True),
    sa.Column('priority_bucket', sa.String(length=50), nullable=True),
    sa.Column('sub_campaign_name', sa.String(length=30), nullable=True),
    sa.Column('campaign_type_code', sa.String(length=20), nullable=True),
    sa.Column('agent_status', sa.String(length=15), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('source_agency_name', sa.String(length=30), nullable=True),
    sa.Column('payment_mode', sa.String(length=5), nullable=True),
    sa.Column('branch_code', sa.String(length=15), nullable=True),
    sa.Column('branch_name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('zone', sa.String(length=30), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('pmt_flag', sa.Boolean(), nullable=False),
    sa.Column('lot_date', sa.Date(), nullable=False),
    sa.Column('dataset_month', sa.Date(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('months_in_campaign', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'lot_date')
    )
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('minio_key', sa.Text(), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reconcile_needed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minio_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('life_campaign_records')
    op.drop_table('health_retention_records')
    op.drop_table('ingestion_batches')
    # ### end Alembic commands ###
