"""Add Debt Collection table

Revision ID: 8a2fac0c50c6
Revises: 1a3b7d21c51d
Create Date: 2026-03-26 12:18:50.373139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a2fac0c50c6'
down_revision: Union[str, Sequence[str], None] = '1a3b7d21c51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('loan_number', sa.String(length=50), nullable=False),
    sa.Column('cust_id', sa.String(length=50), nullable=True),
    sa.Column('source_client_id', sa.String(length=50), nullable=True),
    sa.Column('customer_occupation', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('res_pin_code', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('salutation', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('depositor_mobile_number', sa.String(length=20), nullable=True),
    sa.Column('ref_cust_id', sa.String(length=50), nullable=True),
    sa.Column('paid_to_date', sa.Date(), nullable=True),
    sa.Column('outstanding_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_pos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('emi_os', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('lpp_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bounce_charge', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_penalty_charges', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_dues', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_emi_received', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('loan_disbursal_date', sa.Date(), nullable=True),
    sa.Column('loan_completed', sa.String(length=50), nullable=True),
    sa.Column('loan_tenure', sa.Integer(), nullable=True),
    sa.Column('loan_maturity_date', sa.Date(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('vehicle_name', sa.String(length=150), nullable=True),
    sa.Column('bom_bucket', sa.String(length=50), nullable=True),
    sa.Column('bucket', sa.String(length=50), nullable=True),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('policy_status', sa.String(length=50), nullable=True),
    sa.Column('delinquency_string', sa.String(length=50), nullable=True),
    sa.Column('credit_score', sa.String(length=20), nullable=True),
    sa.Column('propensity_band', sa.String(length=50), nullable=True),
    sa.Column('process_date', sa.Date(), nullable=True),
    sa.Column('lot_date', sa.Date(), nullable=False),
    sa.Column('pmt_flag', sa.Boolean(), nullable=False),
    sa.Column('dataset_month', sa.Date(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'lot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_records')
    # ### end Alembic commands ###
