"""add propensity to insurance tables

Revision ID: c1d2e3f4g5h6
Revises: bf3a92c1d4e7
Create Date: 2026-04-30 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = 'bf3a92c1d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_campaign_records', sa.Column('propensity', sa.String(length=50), nullable=True))
    op.add_column('health_retention_records', sa.Column('propensity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_retention_records', 'propensity')
    op.drop_column('life_campaign_records', 'propensity')
    # ### end Alembic commands ###
