"""add last_logout_at to users

Revision ID: add_last_logout_at
Revises: 16e91fe8571a
Create Date: 2026-04-30 12:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_last_logout_at'
down_revision = '16e91fe8571a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logout_at')
    # ### end Alembic commands ###
